### ISSUE TITLE
Current status of the project

### ISSUE THREAD

**Issue by makcakaya** [gs1oliot/oliot-llrp#1]
What is the current status of project? Is it abandoned?

**Comment by vehumet** [comment]
Dear makcakaya, 
This Oliot-LLRP project is provisionally being suspended, but we can give some support if someone requests.
That's because those features supposed to be updated to Oliot-LLRP (e.g. support other well-known protocols) will be implemented on Oliot-F&C, by design decision.
Of course, other works in Oliot project are still being improved.
